name: grocery_totes
version: 0.0.1
author: Stephen Turley <turley714@gmail.com>
description: Create and share shopping lists
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  rpc: ^0.4.2
  browser: ^0.10.0+2
  polymer: ^0.16.3+1
dev_dependencies:
  test: ^0.12.0
  grinder: ^0.7.0
  mockito: ^0.8.2

